config/routes.rb
Rails.application.routes.draw do

  get 'purchases/index'

  get 'sales/index'

  resources :products
  resources :bids
  resources :categories
  resources :questions
  resources :answers
  resources :sales
  
  post 'bids/new'

  post 'bids/:id' => 'bids#edit' 
  
  get 'contacto/index'

  get 'paginas_estaticas/sobre_nosotros'

  get 'paginas_estaticas/como_funciona'

  get 'paginas_estaticas/tutorial_subir_fotos'

  get 'stats/usuarios_registrados'
  post 'stats/usuarios_registrados'

  get 'stats/ganancias'
  post 'stats/ganancias'

  get 'welcome/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update]

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  include ActiveModel::Validations
	belongs_to :category
	belongs_to :user
	belongs_to :chosen_bid, class_name: "Bid", foreign_key: "chosen_bid_id"
	has_many :questions, dependent: :destroy
	has_many :bids, dependent: :destroy


	scope :by_title, -> sentido { order(title: (((sentido.present?) and (sentido.to_s.downcase == "asc")) ? :asc : :desc))}
	scope :by_created_at, -> sentido { order(created_at: (((sentido.present?) and (sentido.to_s.downcase == "asc")) ? :asc : :desc))}
	scope :by_ends_at, -> sentido { order(ends_at: (((sentido.present?) and (sentido.to_s.downcase == "asc")) ? :asc : :desc))}
	scope :by_finished_at, -> sentido { order(finished_at: (((sentido.present?) and (sentido.to_s.downcase == "asc")) ? :asc : :desc))}

	scope :active_only, -> { where("products.ends_at > ?", Time.now) }
	scope :finished_only, -> { where("products.ends_at < ? and products.chosen_bid_id is not NULL", Time.now) }

	validates :title, :description, :allow_blank => false, :allow_nil => false, :on => :create, presence: true
	#validates :imageURL, :allow_blank => false, :allow_nil => false, :on => :create, presence: true

	def self.search(query)
		consulta1 = where('products.title ilike ? or products.description ilike ?', "%#{query}%", "%#{query}%")
		consulta2 = joins(:category).where("categories.name ilike ?", "%#{query}%")
		arr = consulta1 | consulta2 # Devuelve la unión de los dos conjuntos, pero es un arreglo, NO ES UNA ActiveRecord Relation
		return where(id: arr.map(&:id)) #Conversión a AR Relation... no es lo mejor pero así permite usar scopes
	end

	def self.greater_than(column, date)
		where("? > ?", column, date)
	end

	def self.less_than(column, date)
		where("? > ?", column, date)
	end

	# Permite obtener los productos cuyo valor en la columna especificada en column se
	# encuentre entre td1 y td2. Tener en cuenta que el orden de éstos importa, por lo
	# general, td1 debe ser mayor, en el sentido del tipo de datos, que td2, por ejemplo
	# si se desea buscar entre dos DateTimes, td1 debe ser anterior a td2.
	def self.between(column, td1, td2)
		where("#{column} BETWEEN ? AND ?", td1, td2)
	end

	# Permite saber si ya ha transcurrido el tiempo de la subasta.
	# No indica nada si se ha escogido una oferta o no, sólo hace la comprobación de que el
	# momento actual sea más tardío que el momento especificado para el final de la subasta,
	# si es así, entonces este método devolverá true, de lo contrario false.
	def timeout?
		return Time.now > ends_at
	end

	# Permite saber si la subasta ha finalizado completamente, es decir que si ha transcurrido
	# el tiempo de la subasta y se ha escogido una de todas las ofertas que se le han hecho al
	# producto.
	# Devuelve true si la subasta terminó, en cualquier otro caso false.
	def finished?
		if timeout? and chosen_bid.present?
			return true
		else
			return false
		end
	end

	# Permite obtener las preguntas que actualmente no tienen una respuesta asociada.
	# El tipo devuelto es una ActiveRecord::Relation por lo cual es encadenable con
	# otras consultas de la misma índole, por ejemplo métodos de ActiveRecord::QueryMethods.
	def not_answered_questions
		questions.includes(:answer).where(answers: {id: nil}).references(:answer)
	end

end

app/controllers/products_controller.rb
#encoding: UTF-8
class ProductsController < ApplicationController

  before_action :authenticate_user!, only: [:new,:create,:update,:destroy]
  before_action :product_context, only: [:show, :update]

  def index
  end

  def show

    if (user_signed_in? and current_user != @owner and not current_user.admin) and (@product.finished? or @product.timeout?)
      flash[:alert] = "No tienes autorización para ver este producto."
      redirect_to welcome_index_path
      return;
    end

    if (@product.bids.where(user: current_user).count == 1)
      @temp = true
    else
      @temp = false
    end
  end

  def edit
  end

  def new
    @categories = Category.all

    # Crea un nuevo producto en blanco al entrar a la vista para publicar un nuevo producto
    # Éste servirá para caracterizar el formulario en la vista
    @product = Product.new
  end

  def create
    title = params[:product][:title]
    imgURL = params[:product][:imageURL]
    description = params[:product][:description]
    cat = params[:product][:category_id]

    c = params[:totalDays].to_i
    if c < 15 or c > 30
      @categories = Category.all
      flash.now[:alert] = "La cantidad de días de la subasta está fuera de rango"
      render :new # Vuelvo a mostrar el formulario, esta vez cargado con los datos previamente completados
      return
    end

    fecha_creado = Time.now
    fecha_fin = fecha_creado + c.days

    # A la variable anteriormente creada le asigno el nuevo producto
    @product = Product.create(title: title, description: description, imageURL: imgURL, category_id: cat, user: current_user, created_at: fecha_creado, ends_at: fecha_fin)

    if @product.errors.any?
      @categories = Category.all
      flash.now[:alert] = view_context.generate_html_error(@product)
      render :new # Vuelvo a mostrar el formulario, esta vez cargado con los datos previamente completados
    else
      flash[:notice] = "Producto publicado."
      redirect_to sales_index_path
    end
  end

  def update
    @temp = false
    
    if params[:product].blank? or params[:product][:chosen_bid_id].blank?
      flash.now[:alert] = "No se ha elegido ninguna oferta."
      render :show
      return false
    end

    bid_id = params[:product][:chosen_bid_id].to_i
    chosen_bid =  Bid.find(bid_id)
    
    if @product.timeout? and not @product.finished? and current_user == @owner and chosen_bid.present? and chosen_bid.product == @product
      @product.chosen_bid = chosen_bid
      @product.finished_at = Time.now
      @product.save

      if @product.errors.any?
        flash.now[:alert] = view_context.generate_html_error(@product)
        render :show
      else
        UserMailer.bid_accepted_seller_email(chosen_bid).deliver
        UserMailer.bid_accepted_buyer_email(chosen_bid).deliver
        render :bid_finished
      end
    else
      html = <<-HTML
      <div id="error_explanation">
        <h4>Error al actualizar la oferta ganadora del producto. Se puede deber a:</h4>
        <ul>
          <li>El usuario que esta actualizando la oferta no es creador de la subasta</li>
          <li>La oferta considerada como ganadora no existe</li>
          <li>La oferta considerada como ganadora en realidad corresponde a otro producto</li>
          <li>Todavía no terminó el tiempo para hacer subastas</li>
          <li>Ya se ha elegido una oferta ganadora</li>
        </ul>
      </div>
      HTML
      flash.now[:alert] = html.html_safe
      render :update
    end

    
  end

  def destroy
    @product = current_user.products.find(params[:id])
    @product.destroy
    flash[:notice] = "Producto eliminado."
    redirect_to welcome_index_path
  end

  private

  def product_context
    @product = Product.find(params[:id])
    @owner = @product.user
    @category = @product.category
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/bid_finished.html.erb
<div class="container">
	<h1 class="subtitulos">Subasta finalizada</h1>
	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-8">
		<p><b>¡Felicidades!</b> Has vendido tu producto</p>
		<ul class="list-info">
			<li><b>Título: </b><%= @product.title %></li>
			<li><b>Descripción: </b><%= @product.description.truncate(100) %></li>
			<li><b>Fecha de publicación: </b><%= localize @product.created_at.in_time_zone('Buenos Aires'), format: :long %></li>
			<li><%= link_to "Ir al producto", @product %></li>
		</ul>

		<p> Ha escogido la necesidad <b>"<%= @product.chosen_bid.need %>"</b> valuada en <b><%= @product.chosen_bid.value %> pesos argentinos</b>.

		<p>A continuación le facilitamos los datos del comprador para que pueda contactarse con él para acordar los detalles de la entrega y otras consultas adicionales.</p>
		<ul class="list-info"><% buyer = @product.chosen_bid.user %>
			<li><b>Nombre: </b><%= buyer.first_name %></li>
			<li><b>Apellido: </b><%= buyer.last_name %></li>
			<li><b>Email: </b><%= buyer.email %></li>
			<li><b>País: </b><%= buyer.country_name %></li>
			<li><b>Provincia: </b><%= buyer.province %></li>
			<li><b>Ciudad: </b><%= buyer.city %></li>
			<li><b>Domicilio: </b><%= buyer.domicile %></li>
		</ul>

		<p>De todas formas, se le ha enviado a usted un email con todos los datos necesarios para ponerse en contacto con el comprador, y de igual manera se le ha enviado también un email a este último.</p>
		</div>
		<div class="col-xs-2"></div>
	</div>
</div>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/new.html.erb
<h1 class = "subtitulos">Publicar subasta</h1>
<div class="container">
	<div class = "panel panel-personal">
		<div class = "panel-heading">
			<h3 class = "panel-title">Nueva subasta - <%=current_user.first_name%> <%=current_user.last_name%></h3>
		</div>
		<div class = "panel-body">
			<%= form_for @product do |f| %>
				<div class="form-group negrita">Título de producto: <span class="campo-obligatorio">*</span></div>
				<div class="form-group"><%= f.text_field :title, placeholder: "Título", required: "required", class: "form-control", maxlength: 255 %>
				</div>
				<div class="form-group negrita">Descripción de producto: <span class="campo-obligatorio">*</span></div>
		     	<div class="form-group"><%= f.text_area :description, rows:"6", cols:"100%", :placeholder => "Descripción", :required => "required", class:"form-control", maxlength:"8192" %>
		     	</div>
		     	<div class="form-group negrita">Imagen de producto: </div>
		     	<div class="form-group"><%= f.text_field :imageURL, rows:"15", cols:"100%", :placeholder => "URL de imagen", class:"form-control", maxlength:"255" %>
		     	</div>
		     	<div class="form-group"><span class="negrita">Duración de subasta: </span><span class="italica">(rango válido entre 15 y 30 días)</span></div>
		     	<div class="form-group number-area"><%= number_field_tag :totalDays, 15, in: 15...31, :required => "required", class:"form-control", maxlength:"2" %>
		     	</div>
		     	<div class="form-group negrita">Categoría de producto: </span></div>
		     	<div class="form-group">
					<%= f.select :category_id, options_from_collection_for_select(@categories, "id", "name", selected: (@product.category_id.present? ? @product.category_id : nil)), {}, {class: "form-control", style: "width: auto"} %>
				</div>
		     	<div class="form-group"><%= f.submit "Publicar", class:"btn btn-primary" %></div>
	  		<% end %>
		</div>
		<div class = "panel-footer text-ellipsis">
			<span class="campo-obligatorio">*</span> <span class="error">Campos obligatorios</span>
		</div>
	</div>

	<div class = "panel panel-personal">
		<div class = "panel-heading">
			<h3 class = "panel-title">¿Qué es "URL de imagen"?</h3>
		</div>
		<div class = "panel-body">
			<p>La <span class="negrita">URL de imagen</span> sirve para adjuntar a su publicación una foto de su producto. A continuación, le explicaremos en sencillos pasos cómo subir una imagen.</p>
			<table class="table">
	    		<tr>
	    			<td><span><span class="negrita">1. </span>Entrar al sitio web <a href="http://subefotos.com/" class="destacado">SubeFotos.com</a> (por mayor comodidad, en una nueva pestaña de navegador u otra ventana).</span></td>
	    		</tr>
	    		<tr>
	    			<td><span><span class="negrita">2. </span>Tener almacenada en su computadora la foto del producto que desee subir.</span></td>
	    		</tr>
	    		<tr>
	    			<td><span><span class="negrita">3. </span>Seleccionar la opción <span class="negrita">Examinar</span>, en la parte derecha de la leyenda <span class="negrita">Subir foto</span>.</span></td>
	    		</tr>
	    		<tr>
	    			<td><span><span class="negrita">4. </span>Buscar y seleccionar la imagen de su computadora.</span></td>
	    		</tr>
	    		<tr>
	    			<td><span><span class="negrita">5. </span>Clickear en el botón <span class="destacado">¡SUBIR FOTO!</span></span></td>
	    		</tr>
	    		<tr>
	    			<td><span><span class="negrita">6. </span>Una vez que finalice la carga, el navegador mostrará un sitio con la foto subida en tamaño original, y usted deberá hacer click derecho encima de la imagen y seleccionar la opción <span class="negrita">Copiar dirección de la imagen</span> o <span class="negrita">Copiar URL de imagen</span>.</span></td>
	    		</tr>
	    		<tr>
	    			<td><span><span class="negrita">7. </span>En el cuadro de texto <span class="negrita">URL de imagen</span> deberá hacer click derecho y seleccionar la ópción <span class="negrita">Pegar</span>.</span></td>
	    		</tr>
	    		<tr>
	    			<td><span><span class="negrita">8. </span>¡Listo! Su imagen se subirá junto con toda la información del producto cuando presione el botón <span class="btn btn-primary">Publicar</span></span></td>
	    		</tr>
	  		</table>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<h1 class="subtitulos"><%=@product.title%></h1>
	<div class="panel panel-personal">
		<div class="panel-heading"> 
			<h3 class="panel-title">Detalles del producto</h3>
		</div>
		<div class="panel-body">
			<div><%= image_tag_with_alt(@product.imageURL, alt: @product.title, class: "img-thumbnail centrar imagenes-completas") %></div>
			<div class="espaciar">
				<%= simple_format(@product.description, {}, sanitize: true) %>
			</div>
		</div>
		
		<div class="panel-footer">
			<table class="table">
				<tr>
					<td colspan="2">
						<span class="negrita">Categoría:</span>	<%= @product.category.name %>
					</td>
				</tr>	
				<tr>
					<td colspan="2">
						<span class="negrita">Fecha de publicación:</span>	<%= localize @product.created_at.in_time_zone('Buenos Aires'), format: :long %>
					</td>
				</tr>	
				<tr>
					<td colspan="2">
						<% if @product.timeout? %>
							<% if @product.finished? %>
								<span class="error"> ¡Subasta finalizada! </span>
							<% else %>
								<span class="negrita">Esperando la elección de la oferta ganadora</span>
							<% end %>
						<% else %>
							<span class="negrita">Fecha de finalización:</span>
							<%= localize @product.ends_at.in_time_zone('Buenos Aires'), format: :long %>
						<% end %>
					</td>
				</tr>
				
				<% if user_signed_in? %>
					<% if @owner.email == current_user.email %>
						<% if not @product.finished? %>
							<tr>
								<td>
									<% if @product.timeout? and not @product.finished? %>
										<%= link_to "Elegir necesidad ganadora", "#", data: { toggle: "modal", target: "#modalBids" }, class: "btn btn-primary" %>
										<!-- Modal -->
										<div class="modal fade" id="modalBids" tabindex="-1" role="dialog" aria-labelledby="titleLabel" aria-hidden="true">
										  <div class="modal-dialog">
										    <div class="modal-content">
										      <div class="modal-header">
										        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
										        <h4 class="modal-title" id="titleLabel">Elige la oferta ganadora</h4>
										      </div>
										      <%= form_for @product do |f| %>
										      <div class="modal-body">
										      	<div class="radio-group">
													<% if @product.bids.count == 0 %>
														<div class="negrita">
															<p>Este producto no tiene ofertas.</p>
															<p>Si desea, puede eliminarlo y volverlo a publicar para encontrar nuevos interesados.</p>
														</div>
													<% else %>
														<% @product.bids.each do |bid| %>
														<div class="radio-item">
															<%= f.radio_button(:chosen_bid_id, bid.id) %>
															<%= f.label("chosen_bid_id_" + bid.id.to_s, simple_format(bid.need, {}, sanitize: true), class: "radio-label") %>
														</div>
														<% end %>
														
													<% end %>
												</div>
										      </div>
										      <div class="modal-footer">
										        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
										        <% if @product.bids.count > 0 %>
										        <%= f.submit("Elegir", class: "btn btn-primary", data: {confirm: "¿Estás seguro de tu elección?"}) %>
										        <% end %>
										      </div>
										      <% end %>
										    </div>
										  </div>
										</div>
										<!-- End Modal -->
									<% end %>
								</td>
								
								<td style="text-align:right;" class="text-ellipsis">
									<%= link_to "Eliminar subasta", @product, data: { confirm: "¿Estás seguro?" }, :method => :delete , class:"btn btn-danger" %>
								</td>
							</tr>
						<% end %>
					<% elsif not @product.timeout? %>
						<tr>
							<td style="text-align:right;" class="text-ellipsis">
								<button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal"><%= @temp ? "Modificar oferta" : "Ofertar" %></button>
								<!-- Modal -->
								<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								  <div class="modal-dialog">
								    <div class="modal-content">
								      <div class="modal-header">
								        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
								        <center><h4 class="modal-title negrita" id="myModalLabel">Mi oferta</h4></center>
								      </div>
								      <div class="modal-body" style="text-align: left">

										<div role="tabpanel">

										  <!-- Nav tabs -->
										  <ul class="nav nav-tabs" role="tablist">
										    <li role="presentation" class="active"><a href="#oferta" aria-controls="home" role="tab" data-toggle="tab"><span class="negrita">Ofertar</span></a></li>
										    <li role="presentation"><a href="#actualizarTarjeta" aria-controls="profile" role="tab" data-toggle="tab"><span class="negrita">Actualizar datos de tarjeta</span></a></li>
										  </ul>

										  <!-- Tab panes -->
										  <div class="tab-content">
										    <div role="tabpanel" class="tab-pane active" id="home"></div>
										    <div role="tabpanel" class="tab-pane" id="profile"></div>
										  </div>

										</div>

									    <div id="myTabContent" class="tab-content">
									      <div role="tabpanel" class="tab-pane fade in active" id="oferta" aria-labelledBy="home-tab">
									      		<% if @temp # Hay que modificar oferta %>
											      	<% @bid = current_user.bids.where(product_id: @product.id).last %>
											      	<%= form_for @bid , :as => :bid, method: :edit do |f| %>
											      		<div class="modal-body">
												      		<%= f.hidden_field :id %>
															<div class="form-group">
																<%= label_tag "need", "Necesidad" %>
																<%= f.text_area :need, :disabled => true, class:"form-control", maxlength:"2000" %>
															</div>

															<div class="form-group">
																<%= label_tag "value", "Valor de la oferta (en pesos argentinos)" %>
																<div class="row">
																	<div class="col-xs-4 col-md-4">
																		<div class="input-group">
																			<span class="input-group-addon">$</span>
																			<%= f.number_field :value , :min => 1, :required => "required", class:"form-control", maxlength:"7" %>
																		</div>
																	</div>
																</div>
															</div>

															<div class="form-group">
			 													<%= label_tag "Código de seguridad" %>
																<div class="row">
			    													<div class="col-xs-3 col-md-3" onkeypress="return isNumberKey(event)"><%= password_field_tag :security_code, "", class:"form-control", maxlength:"3", required: true %></div>
			 													</div>
		 													</div>

														</div>
														<div class="form-group modal-footer" style="margin-bottom: 0px;">
															<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
															<%= f.submit "Modificar", class: "btn btn-success" %>
														</div>
											      	<% end %>
									      
										      	<% else # Crear una nueva oferta %>
												    <%= form_tag new_bid_path(product_id_param: @product.id, user_id_param: current_user.id) do %>
														<div class="modal-body">
															<div class="form-group">
																<%= label_tag "need", "Necesidad" %>
																<%= text_area_tag "need", "", :placeholder => "Necesidad", :required => "required", class: "form-control", maxlength: "2000" %>
															</div>

															<div class="form-group">
																<%= label_tag "value", "Valor de la oferta (en pesos argentinos)" %>
																<div class="row">
																	<div class="col-xs-4 col-md-4">
																		<div class="input-group">
																			<span class="input-group-addon">$</span>
																			<%= number_field_tag "value", "", :min => 1, :placeholder => "Valor", :required => "required", class: "form-control", maxlength:"7" %>
																		</div>
																	</div>
																</div>
															</div>

															<div class="form-group">
			 													<%= label_tag "Código de seguridad" %>
																<div class="row">
			    													<div class="col-xs-3 col-md-3" onkeypress="return isNumberKey(event)"><%= password_field_tag :security_code, "", class:"form-control", maxlength:"3", required: true %></div>
			 													</div>
		 													</div>

														</div>
														<div class="form-group modal-footer" style="margin-bottom: 0px;">
															<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
															<%= submit_tag "Publicar", class: "btn btn-success" %>
														</div>

											      	<% end %>
										      	<% end %>	
											
									      </div>
									      <div role="tabpanel" class="tab-pane fade" id="actualizarTarjeta" aria-labelledBy="profile-tab">
									        <%= form_for @current_user, remote: true do |f| %>
									        	<div class="modal-body">
											        <div class="row">
											        	<div id="actualizarTarjeta_msgs" class="col-xs-12" style="margin-top: -1.5em;"></div>
											        </div>

											        <div class="form-group">
											      		<%= f.label "Número de la tarjeta" %>
											      		<div class="row">
														    <div class="col-xs-3 col-md-3" onkeypress="return isNumberKey(event)"><%= f.text_field :card_1 , class:"form-control", maxlength:"4" %></div>
														    <div class="col-xs-3 col-md-3" onkeypress="return isNumberKey(event)"><%= f.text_field :card_2 , class:"form-control", maxlength:"4" %></div>
														    <div class="col-xs-3 col-md-3" onkeypress="return isNumberKey(event)"><%= f.text_field :card_3 , class:"form-control", maxlength:"4" %></div>
														    <div class="col-xs-3 col-md-3" onkeypress="return isNumberKey(event)"><%= f.text_field :card_4 , class:"form-control", maxlength:"4" %></div>
														</div>
													</div>

													<div class="form-group">
														<%= f.label :card_owner_first_name %>
														<div class="row">
	    													<div class="col-xs-6 col-md-6"><%= f.text_field :card_owner_first_name, autofocus: true , class:"form-control" %></div>
	 													</div>
 													</div>

 													<div class="form-group">
	 													<%= f.label :card_owner_last_name %>
														<div class="row">
	    													<div class="col-xs-6 col-md-6"><%= f.text_field :card_owner_last_name, autofocus: true , class:"form-control" %></div>
	 													</div>
 													</div>

 													<div class="form-group">
	 													<%= f.label :expires_on %>
														<div class="row">
															<div class="col-xs-6 col-md-6"><%= f.date_select :expires_on, {:use_month_names => translated_month_names(false), :discard_day => true, :start_year => Date.today.year, :end_year => Date.today.year + 20}, {maxlength: "8", class: "form-control date-select", :required => "required"} %></div>
	 													</div>
 													</div>

													<div class="row negrita small"><div class="col-xs-12" style="text-align: right;">Nota: Todos los campos son obligatorios.</div></div>
													
													<%= hidden_field_tag :product_id, @product.id %>
												</div>
												<div class="form-group modal-footer" style="margin-bottom: 0px;">
													<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
													<%= f.submit "Actualizar" , class:"btn btn-primary" %>
												</div>

											<% end %>

									      </div>
									    </div>
								      </div>
								    </div>
								  </div>
								</div>
								<!-- End Modal -->
							</td>
						</tr>
					<% end %>
				<% end %>
			</table>
		</div>
	</div>
	
	<% if user_signed_in? and (@owner.email == current_user.email or current_user.admin) %>
		<div class="panel panel-personal">
			<div class="panel-heading">
				<h3 class="panel-title">Ofertas</h3>
			</div>
			<ul class="list-group">
				<% if @product.bids.count == 0 %>
					<li class="list-group-item negrita">Este producto no tiene ofertas.</li>
				<% else %>
					<% @product.bids.each do |bid| %>
						<li class="<%= (@product.chosen_bid.present? and @product.chosen_bid == bid) ? "list-group-item active" : "list-group-item" %>">
							<blockquote><%= simple_format(bid.need, {}, sanitize: true) %></blockquote>
						</li>
					<% end %>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="panel panel-personal">
		<div class="panel-heading">
			<h3 class="panel-title">Preguntas y respuestas</h3>
		</div>
		<ul class="list-group list-special">
			<% if @product.questions.length == 0 %>
				<li class="list-group-item negrita">Aún nadie ha hecho una pregunta por este producto.</li>
			<% else %>	
				<% @product.questions.each do |question| %>
					<li class="list-group-item">
						<div><%= question.body %></div>
							<div class="small text-right italica negrita">Pregunta realizada hace <%= time_ago_in_words(question.created_at)%>
						</div>
						<div class="product-answer">
							<% if question.answer == nil %>
								<span class="negrita">Esta pregunta aún no fue respondida.</span>
							<% else %>
								<div><span class="negrita">Respuesta:</span> <%= question.answer.body %></div>
									<div class="small text-right italica negrita">Respuesta de hace <%= time_ago_in_words(question.created_at)%>
								</div>
							<% end %>
						</div>
					</li>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>

app/views/products/update.html.erb
<div class="container">
	<h1 class="subtitulos">Actualización del producto</h1>
</div>